version: "3.2"
services:
  node:
    image: node
    depends_on:
      - mysql
    working_dir: "/usr/app/"
    ports:
      - "3000:3000"
      - "19991:19999"
    volumes:
      - .:/usr/app/
      - ./node_modules:/usr/app/node_modules
    command: "npm start"
  mysql:
    image: mysql:5.6.40
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
