version: "3.2"
services:
  go:
    build: .
    depends_on:
      - gomysql
    ports:
      - "3001:8080"
      - "19993:19999"
    volumes:
      - .:/go/src/github.com/edenriquez/go
    command: "go run main.go"
  gomysql:
    image: mysql:5.6.40
    environment:
      - MYSQL_DATABASE=product
      - MYSQL_ROOT_PASSWORD=rootpassword
